// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using SmallTestsConsole;
using SmallTestsConsole.Models;

namespace SmallTestsConsole
{
    public static partial class ContactOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the SmallTestsConsole.IContactOperations.
        /// </param>
        public static IList<Contact> Get(this IContactOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContactOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the SmallTestsConsole.IContactOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Contact>> GetAsync(this IContactOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<SmallTestsConsole.Models.Contact>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the SmallTestsConsole.IContactOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static IList<Contact> GetById(this IContactOperations operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IContactOperations)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the SmallTestsConsole.IContactOperations.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<Contact>> GetByIdAsync(this IContactOperations operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<SmallTestsConsole.Models.Contact>> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
